apiVersion: v1
kind: Service
metadata:
    name: anildesaisunbirdtelemetryservice
spec:
    type: LoadBalancer
    ports:
    - port: 9001
    selector:
        app: anildesaisunbirdtelemetryservice
